### ISSUE TITLE
Google Docs does not open the generated file

### ISSUE THREAD

**Issue by IonicaBizau** [privateOmega/html-to-docx#1]
Hi! Thank you for this project and keep up the great work.

I generated a hello world docx file with this library but Google Docs simply fails to open it.

![image](https://user-images.githubusercontent.com/2864371/83490917-8675e600-a4b9-11ea-98e3-e8cd714bf36e.png)

If I try to open it with Google Docs, it shows a blank page.

**Comment by privateOmega** [comment]
Hey @IonicaBizau This package isn't yet complete, it still underway but I am sure I can help you with your problem, could you please tell me how did you use this package, if its via npm, the particular version?

**Comment by IonicaBizau** [comment]
I cloned the repository and executed the example, then uploaded the file on Google Drive.

**Comment by privateOmega** [comment]
Hey @IonicaBizau I think I seemed to have the idea why you got an empty document is because if you check the html string fed into the module in example files are empty except for a h1 tag which for some reason I forgot to add support for. Sorry for that.

I plan to add a complete example which would demonstrate all capabilities like images, ordered and unordered lists, headers etc, in the near future as soon as this package is production ready and hope to do it soon.

For your reference, I have posted an html string which you can replace on example-node.js to get a nice docx for trial.
`<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>Document</title>
    </head>
    <body>
        <div>
            <p>Taken from wikpedia</p>
            <img
                src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
    AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
        9TXL0Y4OHwAAAABJRU5ErkJggg=="
                alt="Red dot"
            />
        </div>
        <p>
            <strong>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
                a type specimen book.
            </strong>
            <i>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</i>
            <u>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,</u>and more recently with desktop publishing software
            <span style="color: hsl(0, 75%, 60%);"> like Aldus PageMaker </span>including versions of Lorem Ipsum.
            <span style="background-color: hsl(0, 75%, 60%);">Where does it come from? Contrary to popular belief, Lorem Ipsum is not simply random text.</span>
            It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.
        </p>
        <ul style="list-style-type: circle;">
            <li>Unordered list element</li>
        </ul>
        <ol style="list-style-type: decimal;">
            <li>Ordered list element</li>
        </ol>
    </body>
</html>
`

**Comment by privateOmega** [comment]
Hi @IonicaBizau , I have forthwith updated the examples in the repository with the one I posted above and will be closing the issue, since it doesn't warrant to be open anymore. Please do reopen the issue if you feel the need to or open a new issue.

**Comment by IonicaBizau** [comment]
Thank you very much!
