### ISSUE TITLE
font-size in `pt`: the decimal part is cropped

### ISSUE THREAD

**Issue by erenard** [privateOmega/html-to-docx#114]
The actual regexp to match the font-size in [point](https://github.com/privateOmega/html-to-docx/blob/9b8930fd3e0c5ccce8622ee37d9f63ad1ab796c3/src/utils/unit-conversion.js#L3) doesn't match the decimal part of the font-size.
The workaround is to convert to `px` in the CSS.
We need to use the same regexp for the point and pixel.

**Comment by privateOmega** [comment]
@erenard Not sure, how I got that alone wrong, great catch. I have raised a PR addressing this.
