### ISSUE TITLE
<em> tags from source HTML string not respected on export to Docx

### ISSUE THREAD

**Issue by BrianMagus** [privateOmega/html-to-docx#152]
My use case is a little complex, admittedly - I'm exporting documents out of Draftjs as HTML strings, prepending and appending the HTML header and footer elements, and then exporting from HTML to docx. 

In the exported file, the em tags inside the HTML appear to be stripped out. I dug through the xml templates and did find where they're identified, but I can't tell if they're ever actually inserted into the final docx with the appropriate style tag. 

A snippet of the resulting HTML string from the first part of the process: 
```
<title>Document</title>
</head>
<body>
<h1>Chapter One</h1>
<p><em>Tuesday, May 27th 10:24am</em></p>
<p><em>Pacific Ocean, 30 klicks off the coast of Portland, Oregon, United States</em></p>
<p><em>Deck of the NOAA Ship Bell M. Shimada</em></p>
<p></p>
```

There doesn't seem to be anything in the options that needs to be set, unless I'm missing something. I tried searching and replacing emphasis tags with italic tags, but that didn't change anything in the exported file. 

Is there something I'm missing there?

**Comment by hiitsgabe** [comment]
Hey, what did you do to fix it?

**Comment by hiitsgabe** [comment]
@BrianMagus

**Comment by ccamba** [comment]
Same issue, why closed ?
