### ISSUE TITLE
node-pre-gyp error

### ISSUE THREAD

**Issue by Ant0397** [privateOmega/html-to-docx#16]
Does anyone know what is causing this error? 

Only seems to be when I try to install this package, all others are fine.

Output below:

> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/gagern/node-libtidy/releases/download/v0.4.1/node-v72-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for libtidy-updated@0.4.1 and node@12.18.3 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/antnewman/Desktop/Projects/doc-translator/node_modules/libtidy-updated/lib/tidy.node" "--module_name=tidy" "--module_path=/Users/antnewman/Desktop/Projects/doc-translator/node_modules/libtidy-updated/lib" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/antnewman/Desktop/Projects/doc-translator/node_modules/libtidy-updated
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/antnewman/Desktop/Projects/doc-translator/node_modules/libtidy-updated/lib/tidy.node --module_name=tidy --module_path=/Users/antnewman/Desktop/Projects/doc-translator/node_modules/libtidy-updated/lib --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/antnewman/Desktop/Projects/doc-translator/node_modules/libtidy-updated/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 19.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/antnewman/Desktop/Projects/doc-translator/node_modules/libtidy-updated/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/antnewman/Desktop/Projects/doc-translator/node_modules/libtidy-updated
node-pre-gyp ERR! node -v v12.18.3
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/antnewman/Desktop/Projects/doc-translator/node_modules/libtidy-updated/lib/tidy.node --module_name=tidy --module_path=/Users/antnewman/Desktop/Projects/doc-translator/node_modules/libtidy-updated/lib --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN document-translator@1.0.0 No description
npm WARN document-translator@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libtidy-updated@0.4.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libtidy-updated@0.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Ant0397** [comment]
See slack post for fix 

https://stackoverflow.com/questions/60573595/npm-install-fails-on-node-gyp-rebuild-with-gyp-no-xcode-or-clt-version-detec

**Comment by privateOmega** [comment]
@Ant0397 Thanks for finding the solution.

**Comment by privateOmega** [comment]
@Ant0397 Removed the libtidy dependency, hence this wouldn't be an issue anymore.
