### ISSUE TITLE
CSS functionality missing?

### ISSUE THREAD

**Issue by rickifunk** [privateOmega/html-to-docx#17]
Can only get it to work with inline styling. Is that on purpose?

**Comment by privateOmega** [comment]
@rickifunk Yes thats by design. You could use a package like [juice](https://www.npmjs.com/package/juice) to achieve style inlining from a stylesheet before passing it to html-to-docx.

It's as simple as

```
const styledContentHTMLString = juice.inlineContent(
    contentHTMLString,
    fs.readFileSync(styleFilePath, 'utf-8'),
);
```

**Comment by rickifunk** [comment]
That is pretty sick tbh. Works like a charm!

**Comment by milos5593** [comment]
@privateOmega this works, but some styles are ignored like `line-height`. Is there a workaround to set line-height?

Also is there a possibility to set styles like in this example: [https://docx.js.org/#/usage/styling-with-xml](https://docx.js.org/#/usage/styling-with-xml)

**Comment by privateOmega** [comment]
@milos5593 If you want to apply some styles to your document, what's the easiest would be to use a package like [juice](https://www.npmjs.com/package/juice) to inline the styles and the ones that are supported by html-to-docx will be applied and others will be ignored, unfortunately.

**Comment by leewssam** [comment]
Hi, is there any way to mimic line height or margin-top or padding-top? that can add a possible space in between line?
