### ISSUE TITLE
Not working in node18

### ISSUE THREAD

**Issue by maheshemvigo** [privateOmega/html-to-docx#182]
In node18, the return file is a blob, not a buffer format. My error message is given below,

"TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Blob".

Thank you

**Comment by privateOmega** [comment]
@maheshemvigo Seems like node18 came out with blob in global space, I will refactor the code for node18 to give buffer and not blob.

**Comment by privateOmega** [comment]
@maheshemvigo Please check the latest release and see if it works for you. I am closing the issue for now, but feel free to reopen it if issue persist.
