### ISSUE TITLE
font-weight: bold doesn't work sometimes

### ISSUE THREAD

**Issue by WebPro9369** [privateOmega/html-to-docx#183]
### Example:

```
<p style="text-align: center">
  <span style="
      background-color: transparent;
      color: #000000;
      font-family: 'Times New Roman';
      font-size: 12pt;
      font-weight: bold;
    ">PROBATE –</span><span style="font-weight: bold">&nbsp;</span><span style="
      background-color: transparent;
      color: #000000;
      font-family: 'Times New Roman';
      font-size: 12pt;
    "><span style="text-transform: uppercase; font-weight: bold">NUMBER</span><span
      style="font-weight: bold">DIVISION</span></span>
</p>
```

In this case, "font-weight: bold" doesn't work for words "NUMBER" and "DIVISION", though it seems to be working fine in other cases. I'm wondering <span /> inside another <span /> could be problematic, but not too sure. 
    
Thanks!

**Comment by privateOmega** [comment]
@WebPro9369 Please double check that and see if you are on the latest version of this package. it seems to be working fine for me. Please check the attached screenshot. 
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/10467133/212983797-3a92dba7-fc09-4624-aace-86212166a968.png">

Closing the issue for now, but feel free to reopen it if issue persists.
