### ISSUE TITLE
Add Page Numbers when converting HTML documents to DOCX format

### ISSUE THREAD

**Issue by tvbishan** [privateOmega/html-to-docx#19]
I need to add page numbers on docx document. How can I achieve this? Is **documentOptions** supports for this?

**Comment by amrita-syn** [comment]
Not yet. Page numbers will require the footer to be set up and that is not completely in place yet. Feel free to raise a pr to 'develop' branch

**Comment by privateOmega** [comment]
@tvbishan I have created a PR which addresses the feature that you had requested, page numbering, feel free to check it out. Once PR is merged, this issue will be closed.

**Comment by tvbishan** [comment]
@privateOmega Thanks for your effort. I'll check the PR.
