### ISSUE TITLE
Set table, column width

### ISSUE THREAD

**Issue by danilcostefanovski** [privateOmega/html-to-docx#2]
@privateOmega Can you please explain how to set (table and column), div width in html to affect changes on docx.

**Comment by privateOmega** [comment]
@danilcostefanovski Thanks for showing interest in this library.

Library takes into account **width** from html table's style property. eg `<table border="1" style="width:150px;"><tr><td>sample text</td></tr></table>`. Checkout v1.1.11 if you were using any previous versions. 

For now, column width isn't supported, but I will try to add support for them as soon as possible, but for now if you require uneven cell sizing, I guess maybe you can try out colspan which is supported, else all columns will have equal width.

And sorry to be saying this, but div isn't a topic something that I have solved as of now. So none of the css you have set on div would take effect ATM.

**Comment by amrita-syn** [comment]
The latest changes might mitigate the need to set column width altogether. Looks spacier now.

**Comment by privateOmega** [comment]
@amrita-syn This is something that totally skipped my mind, and will be adding support for it soon. With your latest PR, we now have table min-width also handled.

**Comment by amrita-syn** [comment]
Column (`td` level) widths are now supported by adding `style="...; width: 25%; ..."` to the `td` elements. Closing issue.

**Comment by betaWeb** [comment]
Same problem here : the width of `td` elements is not taken into account and the resulting docx just gives two 50% columns...

**Comment by amrita-syn** [comment]
> Same problem here : the width of `td` elements is not taken into account and the resulting docx just gives two 50% columns...

To be addressed in #105
