### ISSUE TITLE
Images in Libbre office are cropped to single string

### ISSUE THREAD

**Issue by NazarBashinskiy** [privateOmega/html-to-docx#27]
More in my pull request https://github.com/privateOmega/html-to-docx/pull/26

**Comment by privateOmega** [comment]
@NazarBashinskiy I checked out your PR and I don't think that is the solution to the problem that you are facing. I will try to test out the problem you are facing. Also I am open to other solutions, You could use [ECMA-376](https://www.ecma-international.org/publications/standards/Ecma-376.htm) as reference for solutions. Thanks for the attempt and I apologize for the late reply.

**Comment by privateOmega** [comment]
@NazarBashinskiy I tried out the problem you mentioned and it seems only with LibreOffice, the particular problem is cropping up, so I don't really think its a problem that is within scope of this project or OOXML per se, hence please open an issue with LibreOffice, high chance its a problem with their implementation. So I am closing this issue.
