### ISSUE TITLE
a tag in header causes TypeError: Cannot read property 'createDocumentRelationships' of undefined

### ISSUE THREAD

**Issue by wseredynski** [privateOmega/html-to-docx#28]
Hi,
document generation throws an error when header contains a tag eg.
`<h1><a href="https://www.test.com">test</a></h1>`

TypeError: Cannot read property 'createDocumentRelationships' of undefined

**Comment by privateOmega** [comment]
p@wseredynski Oh I am sorry, I guess I haven't added the case of external URL support, I will solve this ASAP.

**Comment by privateOmega** [comment]
@wseredynski 
**Update**: Finally went through the codebase and it seems I forgot to pass one argument to a function. will fix it in the bugfix branch for hyperlink. will test it, merge it and publish it soon.

**Comment by privateOmega** [comment]
@wseredynski This has been fixed and the branch is merged into develop. Will release it soon, along with row-span support.
