### ISSUE TITLE
[Feature Request] <blockquote> support?

### ISSUE THREAD

**Issue by jagzmz** [privateOmega/html-to-docx#36]
As of now, html content containing \<blockquote> tags seems to be omitted in the generated docx file.

**Comment by privateOmega** [comment]
@jagzmz Would you like to contribute that feature to html-to-docx?

**Comment by privateOmega** [comment]
@jagzmz I have added support for blockquote using text justification and indentation, it would be great if you could checkout the [PR](https://github.com/privateOmega/html-to-docx/pull/43) and give review on it.

**Comment by jagzmz** [comment]
> @jagzmz Would you like to contribute that feature to html-to-docx?

Hi, sorry i just saw this, i did went through the code at the time of creating this feature request. Didn't quite get the idea about how should i implement blockquote feature as I haven't worked with openxml things. So I didnt further looked into it.



> @jagzmz I have added support for blockquote using text justification and indentation, it would be great if you could checkout the [PR](https://github.com/privateOmega/html-to-docx/pull/43) and give review on it.

Thanks a lot for this! Would give a review on this soon.

**Comment by privateOmega** [comment]
Will release this feature soon along with row span, hence closing this issue.
