### ISSUE TITLE
How to remove header and footer from first page  of DOCX (html to docx) ?

### ISSUE THREAD

**Issue by jyotisonghare** [privateOmega/html-to-docx#44]
Hello,

We are generating DOCX report into our application for that we used html to docx , html-docx-js node packages and it gives us expected result.
Now, we need to add cover page into first page docx so automatically header/footer will be started from second page but we are not getting any way any attribute which help us to do same.
Please provide some suggestion to fulfill requirement.

Thanks,
Jyoti

**Comment by privateOmega** [comment]
@jyotisonghare At present concept of cover page or skipping headers and footers for the first page isn't something that I have explored.

 Which attributes have you checked so far? And I sincerely hope, the attributes you were checking out were in OOXML context and not the options of html-to-docx. If not, I would suggest checking out headers and footers in OOXML standards, this [PDF](https://www.ecma-international.org/publications/files/ECMA-ST/Office%20Open%20XML%201st%20edition%20Part%205%20(PDF).zip) is for the first edition of that and you could create a PR with a branch from develop for that purpose.

**Comment by jyotisonghare** [comment]
@privateOmega , thanks for your response.

We are creating docx using HTML content. We have to only  remove header and footer from first page i.e. our cover page,  for that I have used - headerType attribute however 'even' and 'first' values are not working only default value work's. 
Adding the below code for your reference:
 const fileBuffer = await HTMLtoDOCX(htmlData, headerString, {
      table: { row: { cantSplit: true } },
      header: true,
      footer: true,
      pageNumber: true,
      font: 'Nunito',
     headerType:'even'
    }, footerString);

Also can you please suggest how can we add the custom CSS for header & footer, where header consist of ( PROJECT NAME + LOGO).

**Comment by privateOmega** [comment]
@jyotisonghare I have added a [PR](https://github.com/privateOmega/html-to-docx/pull/45) for this.

Well custom CSS for header and footer is written in the same way as the document only, inline styles. You could use package like [juice](https://www.npmjs.com/package/juice) in case you want to inline the styles from a css file in your application.

**Comment by jyotisonghare** [comment]
@privateOmega , I have added your PR code into existing package and pass parameter. However it is not working for me would you please correct me where I am doing wrong or please let me know how do I pull your current code 

 const fileBuffer = await HTMLtoDOCX(htmlString, '<p>Header Text Goes Here </p>', {
      title: 'Cover page issue',
      headerType: 'default',
      header: true,
      footerType: 'default',
      footer: true,
      font: 'Nunito',
      fontSize: 22,
      complexScriptFontSize: 22,
      table: {
        row: {
          cantSplit: true,
        },
      },
      pageNumber: true,
      skipFirstHeaderFooter: true,
    } , '<p> Footer Text Goes Here</p>');

**Comment by jyotisonghare** [comment]
@privateOmega , we are waiting for your response.

Thanks,
Jyoti

**Comment by privateOmega** [comment]
@jyotisonghare Could you please post the html-to-docx entry in dependencies of your package.json?

 I am assuming you are still using the version from npm, which doesn't have this change yet because it hasn't been merged, so inorder to access it, you should be doing `npm i git://github.com/privateOmega/html-to-docx#feature/skip-first-header` for now, when I release a new version, you would be getting it from `npm i html-to-docx`

**Comment by privateOmega** [comment]
PR is merged for now, will release a new version by tomorrow after testing.

**Comment by mahendra119** [comment]
Thanks @privateOmega 
We are excited about the release of the new version.

**Comment by mahendra119** [comment]
Hi @privateOmega
Any Updates for the new version release with this fix?

I also tried npm i git://github.com/privateOmega/html-to-docx#feature/skip-first-header, but no dist/code folder present after install.

**Comment by privateOmega** [comment]
@jyotisonghare @mahendra119 Released v1.1.33 now. Closing this issue.

**Comment by mahendra119** [comment]
Thank you very much @privateOmega. You have saved us a lot of time.

**Comment by jyotisonghare** [comment]
@privateOmega  Thank you very much.
