### ISSUE TITLE
How to set custom list style/numbering 

### ISSUE THREAD

**Issue by hsharma1996** [privateOmega/html-to-docx#55]
I have a multi-level list, I want to set custom numbering to each level, can you tell me how that can be done ? 
![image](https://user-images.githubusercontent.com/22193281/108051682-2dfb6e80-7071-11eb-9cea-8e3d4fac570e.png)
This is what I get from library if I add a span in each list to display number. 
Thanks :)

**Comment by privateOmega** [comment]
@hsharma1996 Could you please post the input file you are using along with the html-to-docx configuration as a js file, that would help me understand the issue at hand better.

**Comment by hsharma1996** [comment]
@privateOmega  There is nothing wrong with it. I have a lot of ordered lists and unordered lists in the html, I want the numbering to be manually supplied 
So what you can see in image is, even though i supplied the numbers(1.0,1.1,1.1.1 etc), it is still taking numbering by default 1 2 3.

**Comment by privateOmega** [comment]
@hsharma1996 At present, we don't support this feature, but if somebody could raise a PR for that, I would happily merge it.

**Comment by hsharma1996** [comment]
@privateOmega  maybe some guidance and I could do that myself with some research ?

**Comment by privateOmega** [comment]
@hsharma1996 Sure, have at it. Basic Guideline: Fork the repo and create a branch off of `develop`, namely like `feature/custom-numbering`. I think we should be getting the format as an option and then the numbering fragments should be constructed appropriately. checkout `docx-document.js`, there is a method called `generateNumberingXML`, which does this with default values. I guess that would serve as a starter.

**Comment by osdiab** [comment]
Related to this - my intended use case is to have nested lists have different list style types.

For example,

```
1. foo
2. bar
	a. baz
	b. foo
		i. bar
		ii. baz
```

This is relatively easy to express with style tags, so I'm thinking it would be sufficient for me if this library supported the `list-style-type` rule.

**Comment by privateOmega** [comment]
@osdiab Yes it does,

html input:
```
<ol style="list-style-type:decimal;">
            <li>foo</li>
            <li>bar
                <ol style="list-style-type:lower-alpha;">
                    <li>baz</li>
                    <li>foo
                        <ol style="list-style-type:lower-roman;">
                            <li>bar</li>
                            <li>baz</li>
                        </ol>
                    </li>
                </ol>
            </li>
        </ol>
```

Output looks like this:

![image](https://user-images.githubusercontent.com/10467133/150686858-eb028bfc-4084-49fe-ac14-7565dc0e2ca9.png)

**Comment by privateOmega** [comment]
Closing this issue thread since the feature is supported now.
