### ISSUE TITLE
Custom page size?

### ISSUE THREAD

**Issue by KeithGillette** [privateOmega/html-to-docx#56]
Thanks for this extremely useful library!

I think a useful (and hopefully trivial) improvement would be to support custom paper sizes as a property in the `documentOptions` parameter. I think the maximum page size supported my Microsoft Word is 22"x22". Perhaps instead of passing `orientation`, one could pass `size.height` and `size.width` in any supported unit.

**Comment by privateOmega** [comment]
@KeithGillette Feel free to take it up and raise a PR, its a very simple task and we already have unit conversions written in place and we just have to do those conversions before we generate the document.xml, it shouldn't take any time to wire this feature up. Do tell me if you would like to take it up, else I/someone will take it up asap.

**Comment by KeithGillette** [comment]
Hi @privateOmega. I took a deeper look to investigate raising a PR and see unit conversion functions, but not a central unit detector function to call them and return a normalized size. Am I missing something?

**Comment by privateOmega** [comment]
@KeithGillette Checkout `docx-document.js`, thats where we assign width and height based on the orientation, so before that is called, you could probably do the conversion in `html-to-docx.js`, along with fixing up margins. Keep in mind that we need to preserve existing functionality though.

**Comment by privateOmega** [comment]
Finally got this out in https://github.com/privateOmega/html-to-docx/pull/161. Thanks @KeithGillette @juralio-james . Closing this issue.
