### ISSUE TITLE
How to set continuous line number?

### ISSUE THREAD

**Issue by cooleraid** [privateOmega/html-to-docx#64]
Can we have an option to set a continuous line number in the word document?
(You can also send a guide on how to do that in the code) @privateOmega

**Comment by privateOmega** [comment]
@cooleraid What do you mean continuous line number? maybe an example image and html snippet on what you are trying to achieve would bring more clarity into your question.

**Comment by cooleraid** [comment]
![image](https://user-images.githubusercontent.com/32748319/115604954-ddef9100-a2d9-11eb-9b7e-387f6cc2e4fa.png)
The continuous line numbers are used to number each line of the word document.

**Comment by privateOmega** [comment]
@cooleraid Have created a PR #67  for this feature, hopefully it will get merged soon after review.

**Comment by privateOmega** [comment]
@cooleraid I've merged the corresponding PR, I will be releasing a new version with the feature included. I apologize for the delay. I am closing this issue, but feel free to reopen the issue if you face any issues with the feature.

**Comment by privateOmega** [comment]
released v1.2.2 with this feature.
