### ISSUE TITLE
How to align page number to the bottom right?

### ISSUE THREAD

**Issue by cooleraid** [privateOmega/html-to-docx#65]
Can you please point out how to handle changing the page number from the bottom left to the bottom right? @privateOmega

**Comment by privateOmega** [comment]
@cooleraid its quite easy, just give a footerString containing a `<p></p>` tag with `text-align: right;`

Short snippet on this lifted from example files and modified

```
const fileBuffer = await HTMLtoDOCX(
    htmlString,
    null,
    {
      table: { row: { cantSplit: true } },
      footer: true,
      pageNumber: true,
    },
    `<p style="text-align: right;"></p>`
  );
```

Closing this issue. Feel free to reopen if you need any more clarity on this.

**Comment by KariNabor** [comment]
Hello! I found your comment.
I am trying to bind the page number with more content in the footer, but the page number is pasted with the rest of the content of the footer. 
Can you help me please?
@privateOmega
