### ISSUE TITLE
How to use with webpack / react

### ISSUE THREAD

**Issue by amilich** [privateOmega/html-to-docx#69]
Hi! I'm seeing `Uncaught TypeError: fs.readFileSync is not a function`. Any suggestions? Have tried importing from `dist` in addition to the normal package.

**Comment by amilich** [comment]
@privateOmega is https://github.com/privateOmega/html-to-docx/pull/68 intended to address this?

**Comment by amilich** [comment]
Duplicate of https://github.com/privateOmega/html-to-docx/issues/3

**Comment by privateOmega** [comment]
@amilich How have you installed the package? try the steps mentioned towards the end in #3

**Comment by amilich** [comment]
> @amilich How have you installed the package? try the steps mentioned towards the end in #3

I've tried, I now see `Internal Error: Invalid descriptor (https://github.com/privateOmega/html-to-docx.git#feature/browser-example)` on yarn2

**Comment by privateOmega** [comment]
@amilich `yarn add <package name>@git+ssh://<git remote URL>#semver:^3.2.0` this is the format for yarn2, not `yarn add url`. You have to explicitly specify package name I guess.

Lifted from here https://github.com/yarnpkg/berry/issues/994#issuecomment-628586986

**Comment by amilich** [comment]
> @amilich `yarn add <package name>@git+ssh://<git remote URL>#semver:^3.2.0` this is the format for yarn2, not `yarn add url`. You have to explicitly specify package name I guess.
> 
> Lifted from here [yarnpkg/berry#994 (comment)](https://github.com/yarnpkg/berry/issues/994#issuecomment-628586986)

yarn add html-to-docx@git://github.com/privateOmega/html-to-docx.git#feature/browser-example seems to have worked!

**Comment by amilich** [comment]
> > @amilich `yarn add <package name>@git+ssh://<git remote URL>#semver:^3.2.0` this is the format for yarn2, not `yarn add url`. You have to explicitly specify package name I guess.
> > Lifted from here [yarnpkg/berry#994 (comment)](https://github.com/yarnpkg/berry/issues/994#issuecomment-628586986)
> 
> yarn add html-to-docx@git://github.com/privateOmega/html-to-docx.git#feature/browser-example seems to have worked!

Still seeing package unable to be resolved... not sure what's up. Have had issues adding via GH urls before

**Comment by amilich** [comment]
> @amilich `yarn add <package name>@git+ssh://<git remote URL>#semver:^3.2.0` this is the format for yarn2, not `yarn add url`. You have to explicitly specify package name I guess.
> 
> Lifted from here [yarnpkg/berry#994 (comment)](https://github.com/yarnpkg/berry/issues/994#issuecomment-628586986)

Do you plan on merging https://github.com/privateOmega/html-to-docx/pull/68 soon?

**Comment by privateOmega** [comment]
@amilich Please test with latest version 1.2.1.
