### ISSUE TITLE
List of supported style

### ISSUE THREAD

**Issue by novecento** [privateOmega/html-to-docx#73]
Hi, do we have a list of supported styles?
To understand what can I do :-)
Thanks.

**Comment by privateOmega** [comment]
@novecento What do you mean by supported styles? do you mean css styles?

**Comment by novecento** [comment]
> @novecento What do you mean by supported styles? do you mean css styles?

Yes, I mean if you have a list of css styles that I can use :-)

**Comment by privateOmega** [comment]
@novecento Sorry, I haven't compiled a list, and it would take me sometime to compile one, which I can't commit for at present. Maybe give it a look through the source code and you would get the idea of things currently supported.
