### ISSUE TITLE
Leading and Trailing spaces

### ISSUE THREAD

**Issue by simon-jouet** [privateOmega/html-to-docx#74]
Hi there,

Thanks for the library, this is a great time saver.

I'm running a bit into an issue. I have a paragraph `<p>` that gets converted properly but I would like to indent the first line of the paragraph by 3 spaces.

My first attempt was using a `margin-left` which doesn't look to be supported. I then tried to go the dumb way and use cheerio to add three space characters after the `<p>` which works in the HTML but it looks like html-to-docx is trimming the text

Any pointers on how to go about this?

Thanks

**Comment by privateOmega** [comment]
@simon-jouet Well normal space gets trimmed, but I guess a solution for you could be usign &nbsp; and I don't think it gets trimmed out. Do tell how it goes.

**Comment by simon-jouet** [comment]
Thanks @privateOmega for the reply, I had tried &nbsp; and just tried again it kind of works but it's also rendered differently. In libreoffice at least it's rendered as a gray space 

![image](https://user-images.githubusercontent.com/832495/121004974-35ad6300-c787-11eb-8589-309c5466f7ad.png)

**Comment by privateOmega** [comment]
@simon-jouet &nbsp; is kind of the cleanest approach I could think of. Please check if that same grey space is there on other word processors? I tested this on  wps for mac, and it doesn't seem to have this issue. Also closing the issue since its not relevant enough for html-to-docx.
