### ISSUE TITLE
Export CSS style

### ISSUE THREAD

**Issue by ghilaslinz** [privateOmega/html-to-docx#77]
Hello, @privateOmega 

I would like to thank you for the last issue you resolved to me.

I have a question how i can also export the CSS style.

What should i add to also export CSS style ?

```

import HTMLtoDOCX from 'html-to-docx';
import { save } from 'save-file';
import "./App.css";

const htmlString = `<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>Document</title>
    </head>
    <body>
        <div className="style">    
        <p> Hello </p>
        </div>
    </body>
</html>`;

const downloadFile = async () => {
  const fileBuffer = await HTMLtoDOCX(htmlString, null, {
    table: { row: { cantSplit: true } },
    footer: true,
    pageNumber: true,
  });

  await save(fileBuffer, 'trial.docx')
};

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <button onClick={downloadFile}>HELLO</button>
      </header>
    </div>
  );
}

export default App;


```

**Comment by privateOmega** [comment]
@ghilaslinz What do you mean by exporting css? in this package, we just generate the docx file, thats it. But if you mean apply css from external file onto html for those to reflect in docx, use [juice](https://www.npmjs.com/package/juice), that is what I use.

**Comment by ghilaslinz** [comment]
hello @privateOmega,

Yes it is what i mean apply css from external file onto html for those to reflect in docx.
Do you have a snippet code to apply juice to a react component 

Best regards

**Comment by privateOmega** [comment]
@ghilaslinz Please check for an example in the juice repo. This is what I use `juice.inlineContent(contentHTMLString, styleFileContent)`. Also closing the issue since its not relevant to html-to-docx.
