### ISSUE TITLE
Direction not supported?

### ISSUE THREAD

**Issue by gazu36** [privateOmega/html-to-docx#80]
Trying to set `<body dir="rtl">` and it keeps the document LTR

**Comment by privateOmega** [comment]
@gazu36 Sorry, we don't yet support rtl, and definitely don't support reading dir attribute of body tag. I had attempted at rtl once in #40 . I am closing this issue in favor of that, so we have a single place to keep track of.

**Comment by ammarmohamed2016** [comment]
Any update about direction support ? @privateOmega
