### ISSUE TITLE
List inside table not working

### ISSUE THREAD

**Issue by casperon** [privateOmega/html-to-docx#83]
If we add list inside a table, then the result not showing the contents of list tag. Is this known issue? or we need to do any workaround to achieve this? Any suggestions would be helpful.

**Comment by privateOmega** [comment]
@casperon Yes this is a known issue, which needs to be worked on, but unfortunately I won't be able to spare anytime soon. Would really appreciate PR for this.

**Comment by kurukururuu** [comment]
+1. though I am currently working for it right now.

**Comment by privateOmega** [comment]
@kurukururuu Thanks for the help, please raise a PR off of develop and I will merge it after testing.

**Comment by privateOmega** [comment]
Closing this since its already addressed in #111
